import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  emitThemeRuntimeGeneratedSource,
  writeThemeRuntimeFromConfig,
} from '../src/generate-theme-runtime.js';
import { readReact33ThemeConfig } from '../src/read-react33-theme-config.js';

describe('readReact33ThemeConfig', () => {
  it('returns null when section is missing', () => {
    expect(readReact33ThemeConfig({})).toBeNull();
  });

  it('parses react33Theme block', () => {
    expect(
      readReact33ThemeConfig({
        react33Theme: {
          cookieName: 'demo-theme',
          persistenceMode: 'cookie',
          generatedRuntimeOutput: './out/theme.runtime.generated.ts',
        },
      }),
    ).toEqual({
      cookieName: 'demo-theme',
      persistenceMode: 'cookie',
      generatedRuntimeOutput: './out/theme.runtime.generated.ts',
    });
  });
});

describe('emitThemeRuntimeGeneratedSource', () => {
  it('emits persistenceEnvKey when configured', () => {
    const source = emitThemeRuntimeGeneratedSource(
      { persistenceEnvKey: 'NEXT_PUBLIC_THEME_PERSISTENCE' },
      './styles.generated',
    );
    expect(source).toContain('persistenceEnvKey: "NEXT_PUBLIC_THEME_PERSISTENCE"');
  });

  it('emits persistence and createThemeRuntime wiring', () => {
    const source = emitThemeRuntimeGeneratedSource(
      {
        cookieName: 'demo-theme',
        persistenceMode: 'cookie',
      },
      './styles.generated',
    );
    expect(source).toContain('import { styles, type ThemeName } from "./styles.generated"');
    expect(source).toContain('createThemePersistence');
    expect(source).toContain('createThemeRuntime');
    expect(source).toContain('persistenceEnvKey: "REACT33_THEME_PERSISTENCE"');
    expect(source).toContain('export const persistTheme');
  });

  it('omits persistenceEnvKey when config sets empty string', () => {
    const source = emitThemeRuntimeGeneratedSource(
      { persistenceEnvKey: '' },
      './styles.generated',
    );
    expect(source).not.toContain('persistenceEnvKey:');
  });
});

describe('writeThemeRuntimeFromConfig', () => {
  it('writes theme.runtime.generated.ts', () => {
    const root = mkdtempSync(join(tmpdir(), 'react-theme-gen-'));
    writeFileSync(
      join(root, 'react33.config.json'),
      JSON.stringify({
        react33Theme: {
          cookieName: 't',
          generatedRuntimeOutput: './out/theme.runtime.generated.ts',
          stylesGeneratedImport: './styles.generated.ts',
        },
      }),
    );
    writeFileSync(join(root, 'styles.generated.ts'), 'export const styles = {} as const;\n');

    const result = writeThemeRuntimeFromConfig({ configPath: join(root, 'react33.config.json') });
    expect(result.skipped).toBe(false);
    const out = readFileSync(join(root, 'out/theme.runtime.generated.ts'), 'utf8');
    expect(out).toContain('GENERATED by react-theme-generate');
    expect(out).toContain('createThemeRuntime');
  });
});
