import { relative } from 'node:path';
import type { OpenApiFileConfig } from './config-types';
import { generateInitDataModuleSource, collectReferencedInitDataSymbols } from './init-data';
import { operationIdToPascal, scopeToPascal } from './naming';
import { parseOpenApiFile, type ParsedOperation } from './parse-openapi';
import {
  buildOperationParamsSchema,
  schemaToZodExpr,
  type SchemaContext,
} from './schema-to-zod';
import { formatSecurityJSDoc, resolveOperationSecurity } from './security-meta';
import { resolveOpenApiValidateConfig } from './validation.js';

const BANNER = '/* Generated by react-networking-generate — do not edit. */';

export type OpenApiBundleOutput = {
  zodSource: string;
  typesSource: string;
  sdkSource: string;
  hooksSource: string;
  initDataSource: string | null;
};

function relImport(fromDir: string, toFile: string): string {
  let rel = relative(fromDir, toFile).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel.replace(/\.tsx?$/, '');
}

export function generateZodModuleSource(
  parsed: Awaited<ReturnType<typeof parseOpenApiFile>>,
): string {
  const ctx: SchemaContext = {
    schemas: parsed.schemas,
    emitted: new Set(),
    lines: [
      BANNER,
      "import { z } from 'zod';",
      '',
    ],
  };

  for (const op of parsed.operations) {
    const pascal = operationIdToPascal(op.operationId);
    const paramsSchema = buildOperationParamsSchema(
      ctx,
      pascal,
      op.pathParams,
      op.queryParams,
      op.bodySchema,
      op.bodySchemaName,
    );
    ctx.lines.push(`export const ${pascal}ParamsSchema = ${paramsSchema};`);

    if (op.responseSchema && op.hasBody) {
      const dataSchema = schemaToZodExpr(ctx, op.responseSchema, `${pascal}Data`);
      ctx.lines.push(`export const ${pascal}DataSchema = ${dataSchema};`);
    } else if (op.successStatus === '204') {
      ctx.lines.push(`export const ${pascal}DataSchema = z.null();`);
    }
  }

  return ctx.lines.join('\n');
}

export function generateTypesModuleSource(
  zodPath: string,
  parsed: Awaited<ReturnType<typeof parseOpenApiFile>>,
  typesDir: string,
): string {
  const zodImport = relImport(typesDir, zodPath);
  const lines: string[] = [
    BANNER,
    "import type { OpenApiHookOverrides } from '@react33/react-networking';",
    `import {`,
  ];

  const imports: string[] = [];
  for (const op of parsed.operations) {
    const pascal = operationIdToPascal(op.operationId);
    imports.push(`  ${pascal}ParamsSchema`);
    imports.push(`  ${pascal}DataSchema`);
  }

  lines.push(imports.join(',\n'));
  lines.push(`} from '${zodImport}';`);
  lines.push(`import { z } from 'zod';`);
  lines.push('');

  for (const op of parsed.operations) {
    const pascal = operationIdToPascal(op.operationId);
    lines.push(`export type ${pascal}Params = z.infer<typeof ${pascal}ParamsSchema>;`);
    lines.push(`export type ${pascal}Data = z.infer<typeof ${pascal}DataSchema>;`);
    lines.push(
      `export type ${pascal}HookOverrides = OpenApiHookOverrides<${pascal}Params, ${pascal}Data>;`,
    );
    lines.push('');
  }

  return lines.join('\n');
}

function buildSdkFunction(
  op: ParsedOperation,
  scope: string,
  document: Record<string, unknown>,
  fileConfig: OpenApiFileConfig,
): string {
  const pascal = operationIdToPascal(op.operationId);
  const meta = resolveOperationSecurity(op.operation, document, op.pathLevelSecurity);
  const jsdoc = formatSecurityJSDoc(meta, scope);
  const opCfg = fileConfig.operations?.[op.operationId] ?? {};
  const verboseDefault = opCfg.verbose ?? fileConfig.defaults?.verbose ?? false;
  const validateDefaults = resolveOpenApiValidateConfig(
    fileConfig.defaults?.validate,
    fileConfig.validate,
    opCfg.validate,
  );
  const validateJson = JSON.stringify(validateDefaults);

  const paramsValidateBlock = `  if (validateOpts.params) {
    requestParams = validateOpenApiParams(${pascal}ParamsSchema, params, {
      operationId: ${JSON.stringify(op.operationId)},
      schemaName: ${JSON.stringify(`${pascal}ParamsSchema`)},
      direction: 'params',
      mode: validateOpts.mode,
      verbose,
      scope: ${JSON.stringify(scope)},
      method: ${JSON.stringify(op.method)},
      url: ${JSON.stringify(op.pathTemplate)},
    });
  }`;

  const responseValidateBlock =
    op.hasBody && op.successStatus !== '204'
      ? `    if (validateOpts.response) {
      return validateOpenApiResponse(${pascal}DataSchema, res, {
        operationId: ${JSON.stringify(op.operationId)},
        schemaName: ${JSON.stringify(`${pascal}DataSchema`)},
        direction: 'response',
        mode: validateOpts.mode,
        verbose,
        scope: ${JSON.stringify(scope)},
        method: ${JSON.stringify(op.method)},
        url: ${JSON.stringify(op.pathTemplate)},
      });
    }
    return res;`
      : `    return res;`;

  return `${jsdoc}
export const ${op.operationId}ValidateDefaults = ${validateJson} as const;

export async function ${op.operationId}(
  params: ${pascal}Params,
  options?: OpenApiSdkCallOptions,
): Promise<RequestReturn<${pascal}Data>> {
  const validateOpts = resolveOpenApiSdkValidate(${op.operationId}ValidateDefaults, options?.validate);
  const verbose = options?.verbose ?? ${verboseDefault};
  let requestParams = params;
${paramsValidateBlock}
  const { url, body } = resolveOpenApiRequest(${JSON.stringify(op.pathTemplate)}, ${JSON.stringify(op.method)}, requestParams);
  return ${scope}Request({
    url,
    method: ${JSON.stringify(op.method)},
    body,
  }).then((res) => {
${responseValidateBlock}
  }) as Promise<RequestReturn<${pascal}Data>>;
}

export const ${op.operationId}OpenApiMeta = {
  operationId: ${JSON.stringify(op.operationId)},
  isPublic: ${meta.isPublic},
  securitySchemes: ${JSON.stringify(meta.schemeNames)},
} as const;
`;
}

export function generateSdkModuleSource(
  parsed: Awaited<ReturnType<typeof parseOpenApiFile>>,
  fileConfig: OpenApiFileConfig,
  paths: { zod: string; types: string; apis: string },
  sdkDir: string,
): string {
  const zodImport = relImport(sdkDir, paths.zod);
  const typesImport = relImport(sdkDir, paths.types);
  const apisImport = relImport(sdkDir, paths.apis);
  const scope = fileConfig.scope;

  const zodNames = parsed.operations.flatMap((op) => {
    const p = operationIdToPascal(op.operationId);
    return op.hasBody ? [`${p}DataSchema`] : [];
  });

  const lines: string[] = [
    BANNER,
    `import { resolveOpenApiRequest, validateOpenApiParams, validateOpenApiResponse, resolveOpenApiSdkValidate, type OpenApiSdkCallOptions } from '@react33/react-networking';`,
    `import type { RequestReturn } from '@react33/react-networking';`,
    `import { ${scope}Request } from '${apisImport}';`,
    `import { ${zodNames.length ? `${zodNames.join(', ')}, ` : ''}${parsed.operations.map((o) => `${operationIdToPascal(o.operationId)}ParamsSchema`).join(', ')} } from '${zodImport}';`,
    `import type { ${parsed.operations.map((o) => `${operationIdToPascal(o.operationId)}Params, ${operationIdToPascal(o.operationId)}Data`).join(', ')} } from '${typesImport}';`,
    '',
  ];

  for (const op of parsed.operations) {
    lines.push(buildSdkFunction(op, scope, parsed.document, fileConfig));
  }

  return lines.join('\n');
}

function resolveHookInitData(
  op: ParsedOperation,
  fileConfig: OpenApiFileConfig,
  initDataImport: string | null,
): { initDataLine: string; initDataImport?: string } {
  const opCfg = fileConfig.operations?.[op.operationId];
  if (opCfg?.initData === false) return { initDataLine: '' };
  if (typeof opCfg?.initData === 'string' && initDataImport) {
    return {
      initDataLine: `initData: ${opCfg.initData},`,
      initDataImport,
    };
  }
  return { initDataLine: '' };
}

export function generateHooksModuleSource(
  parsed: Awaited<ReturnType<typeof parseOpenApiFile>>,
  fileConfig: OpenApiFileConfig,
  paths: { sdk: string; types: string; apisHooks: string; initData?: string },
  hooksDir: string,
): string {
  const sdkImport = relImport(hooksDir, paths.sdk);
  const typesImport = relImport(hooksDir, paths.types);
  const apisHooksImport = relImport(hooksDir, paths.apisHooks);
  const initDataRel = paths.initData ? relImport(hooksDir, paths.initData) : null;
  const scopePascal = scopeToPascal(fileConfig.scope);
  const defaults = fileConfig.defaults ?? {};

  const initImports = new Set<string>();
  const hookBlocks: string[] = [];

  for (const op of parsed.operations) {
    const pascal = operationIdToPascal(op.operationId);
    const opCfg = fileConfig.operations?.[op.operationId] ?? {};
    const fetchOnMount = opCfg.fetchOnMount ?? defaults.fetchOnMount ?? false;
    const verbose = opCfg.verbose ?? defaults.verbose ?? false;
    const { initDataLine, initDataImport } = resolveHookInitData(op, fileConfig, initDataRel);
    if (initDataImport && typeof opCfg.initData === 'string') {
      initImports.add(opCfg.initData);
    }

    const meta = resolveOperationSecurity(op.operation, parsed.document, op.pathLevelSecurity);
    const jsdoc = formatSecurityJSDoc(meta, fileConfig.scope);

    hookBlocks.push(`${jsdoc}
export function use${pascal}(
  options?: ${pascal}HookOverrides,
  watch: unknown[] = [],
) {
  return use${scopePascal}Request<${pascal}Params, ${pascal}Data>({
    name: ${JSON.stringify(op.operationId)},
    url: ${JSON.stringify(op.pathTemplate)},
    method: ${JSON.stringify(op.method)},
    fetchOnMount: ${fetchOnMount},
    verbose: ${verbose},
    ${initDataLine}
    action: async (params) => ${op.operationId}(params as ${pascal}Params, { verbose: options?.verbose ?? ${verbose} }) as Promise<RequestReturn<${pascal}Data>>,
    ...options,
  }, watch);
}
`);
  }

  const lines: string[] = [
    "'use client';",
    BANNER,
    `import { use${scopePascal}Request } from '${apisHooksImport}';`,
    `import type { RequestReturn } from '@react33/react-networking';`,
    `import type { ${parsed.operations.map((o) => `${operationIdToPascal(o.operationId)}HookOverrides, ${operationIdToPascal(o.operationId)}Params, ${operationIdToPascal(o.operationId)}Data`).join(', ')} } from '${typesImport}';`,
    `import { ${parsed.operations.map((o) => o.operationId).join(', ')} } from '${sdkImport}';`,
  ];

  if (initImports.size > 0 && initDataRel) {
    lines.push(`import { ${[...initImports].join(', ')} } from '${initDataRel}';`);
  }

  lines.push('');
  lines.push(...hookBlocks);

  return lines.join('\n');
}

export async function generateOpenApiBundle(
  specAbsPath: string,
  fileConfig: OpenApiFileConfig,
  outputPaths: {
    zod: string;
    types: string;
    sdk: string;
    hooks: string;
    initData?: string;
    apis: string;
    apisHooks: string;
  },
): Promise<OpenApiBundleOutput> {
  const parsed = await parseOpenApiFile(specAbsPath, fileConfig);

  const zodSource = generateZodModuleSource(parsed);
  const typesSource = generateTypesModuleSource(outputPaths.zod, parsed, dirnameOf(outputPaths.types));
  const sdkSource = generateSdkModuleSource(parsed, fileConfig, {
    zod: outputPaths.zod,
    types: outputPaths.types,
    apis: outputPaths.apis,
  }, dirnameOf(outputPaths.sdk));
  const hooksSource = generateHooksModuleSource(parsed, fileConfig, {
    sdk: outputPaths.sdk,
    types: outputPaths.types,
    apisHooks: outputPaths.apisHooks,
    initData: outputPaths.initData,
  }, dirnameOf(outputPaths.hooks));

  let initDataSource: string | null = null;
  if (fileConfig.initData?.generate && outputPaths.initData) {
    initDataSource = generateInitDataModuleSource(
      parsed.operations,
      { schemas: parsed.schemas, emitted: new Set(), lines: [] },
      relImport(dirnameOf(outputPaths.initData), outputPaths.types),
    );
  }

  const requiredSymbols = collectReferencedInitDataSymbols(parsed.operations, fileConfig.operations);
  if (requiredSymbols.size > 0 && !fileConfig.initData?.generate) {
    // validation happens at write time if file missing — skip here
  }

  return { zodSource, typesSource, sdkSource, hooksSource, initDataSource };
}

function dirnameOf(filePath: string): string {
  return filePath.replace(/[/\\][^/\\]+$/, '');
}

export { parseOpenApiFile };
