import type { ParsedOperation } from './parse-openapi';
import { operationIdToPascal, schemaNameToEmptyConstant } from './naming';
import type { SchemaContext } from './schema-to-zod';

/** Minimal JSON-like literal from schema for init-data constants (bootstrap). */
export function schemaToEmptyLiteral(schema: Record<string, unknown> | null, depth = 0): string {
  if (!schema || depth > 8) return '{}';
  if (schema.$ref && typeof schema.$ref === 'string') {
    return '{}';
  }
  if (schema.enum && Array.isArray(schema.enum) && schema.enum.length > 0) {
    return JSON.stringify(schema.enum[0]);
  }
  if (schema.default !== undefined) {
    return JSON.stringify(schema.default);
  }
  const type = schema.type;
  const types = Array.isArray(type) ? type.filter((t) => t !== 'null') : type ? [type] : [];

  if (types.includes('array') || schema.items) {
    return '[]';
  }
  if (types.includes('boolean')) {
    return 'false';
  }
  if (types.includes('integer') || types.includes('number')) {
    if (typeof schema.minimum === 'number') return String(schema.minimum);
    return '0';
  }
  if (types.includes('string')) {
    return "''";
  }
  if (types.includes('object') || schema.properties) {
    const props = schema.properties as Record<string, Record<string, unknown>> | undefined;
    if (!props) return '{}';
    const required = (schema.required as string[] | undefined) ?? Object.keys(props);
    const fields = required.map((key) => {
      const val = schemaToEmptyLiteral(props[key], depth + 1);
      return `${key}: ${val}`;
    });
    return `{ ${fields.join(', ')} }`;
  }
  return '{}';
}

export function generateInitDataModuleSource(
  operations: ParsedOperation[],
  ctx: SchemaContext,
  typeImportPath: string,
): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '/* Generated by react-networking-generate — do not edit. */',
    '',
  ];

  const emitted = new Set<string>();
  const typeNames = new Set<string>();
  const exports: string[] = [];

  for (const op of operations) {
    if (!op.hasBody || op.successStatus === '204') continue;
    const dataTypeName = `${operationIdToPascal(op.operationId)}Data`;
    const constName =
      typeof op.responseSchemaName === 'string'
        ? schemaNameToEmptyConstant(op.responseSchemaName)
        : `empty${dataTypeName}`;
    if (emitted.has(constName)) continue;
    emitted.add(constName);
    typeNames.add(dataTypeName);
    const literal = schemaToEmptyLiteral(op.responseSchema);
    exports.push(`export const ${constName} = ${literal} satisfies ${dataTypeName};`);
    exports.push('');
  }

  if (typeNames.size > 0) {
    lines.push(`import type { ${[...typeNames].join(', ')} } from '${typeImportPath}';`);
    lines.push('');
  }

  lines.push(...exports);

  if (emitted.size === 0) {
    lines.push('export {};');
  }

  return lines.join('\n');
}

export function collectReferencedInitDataSymbols(
  operations: ParsedOperation[],
  operationsConfig: Record<string, { initData?: string | false }> | undefined,
): Set<string> {
  const symbols = new Set<string>();
  for (const op of operations) {
    const cfg = operationsConfig?.[op.operationId];
    if (cfg?.initData && typeof cfg.initData === 'string') {
      symbols.add(cfg.initData);
    }
  }
  return symbols;
}
