/* eslint-disable */
/* Generated by react-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@react33/react-networking';
import { apiRuntime } from "./api.runtime.client";

const baseDefinitions = {
  pokemon: {
    url: "https://pokeapi.co/api/v2",
    headers: {"Accept":"application/json"},
    cache: "no-store",
    credentials: "omit",
  },
} satisfies Record<string, ApiClientConfigBody>;

export const definitions = apiRuntime.defineDefinitions(baseDefinitions);

export const apis = createApiRegistry(definitions, {
  load: apiRuntime.load,
  defaults: apiRuntime.defaults,
});

export type ApiNames = keyof typeof apis;
export const pokemonRequest = apis.pokemon;
