'use client';

/* Generated by lib-networking-generate — do not edit */

import { useAsyncFetch, type DynamicOptions, type RequestReturn } from '@lib/networking';
import { apis } from './apis.generated';

export function usePokemonRequest<Params, Data, Response = null>(
  settings: DynamicOptions<Params, Data, Response>,
  watch: any[],
) {
  const { url = '/', method = 'GET' } = settings;
  return useAsyncFetch<Params, Data, Response>(
    {
      ...settings,
      action: async (params?: Params) =>
        apis.pokemon({ url, method, body: params }) as unknown as Promise<RequestReturn<Data>>,
    },
    watch,
  );
}
