/* eslint-disable */
/* Generated by react-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@react33/react-networking';
import { apiRuntime } from "./session.runtime.generated";

const baseDefinitions = {
  billing: {
    url: "https://billing.example.com",
    headers: {"Accept":"application/json"},
    cache: "no-store",
  },
  reports: {
    url: "https://reports.partner.example.com",
    headers: {"Accept":"application/json"},
    cache: "no-store",
  },
  pokemon: {
    url: "https://pokeapi.co/api/v2",
    headers: {"Accept":"application/json"},
    cache: "no-store",
    credentials: "omit",
  },
} satisfies Record<string, ApiClientConfigBody>;

export const definitions = apiRuntime.defineDefinitions?.(baseDefinitions) ?? baseDefinitions;

export const apis = createApiRegistry(definitions, {
  load: apiRuntime.load,
  loads: apiRuntime.loads,
  defaults: apiRuntime.defaults,
  defaultsByApi: apiRuntime.defaultsByApi,
});

export type ApiNames = keyof typeof apis;
export const billingRequest = apis.billing;
export const reportsRequest = apis.reports;
export const pokemonRequest = apis.pokemon;
