/* eslint-disable */
/* Generated by lib-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@lib/networking';

export const definitions = {
  pokemon: {
    url: "https://pokeapi.co/api/v2",
    headers: {"Accept":"application/json"},
    cache: "no-store",
  },
} satisfies Record<string, ApiClientConfigBody>;

export const apis = createApiRegistry(definitions, {
  load: async (shared) => shared,
});

export type ApiNames = keyof typeof apis;
export const pokemonRequest = apis.pokemon;
