/* Generated by react-networking-generate — do not edit. */
import type { OpenApiHookOverrides } from '@react33/react-networking';
import {
  PokemonListParamsSchema,
  PokemonListDataSchema,
  PokemonRetrieveParamsSchema,
  PokemonRetrieveDataSchema
} from './pokemon.openapi.zod';
import { z } from 'zod';

export type PokemonListParams = z.infer<typeof PokemonListParamsSchema>;
export type PokemonListData = z.infer<typeof PokemonListDataSchema>;
export type PokemonListHookOverrides = OpenApiHookOverrides<PokemonListParams, PokemonListData>;

export type PokemonRetrieveParams = z.infer<typeof PokemonRetrieveParamsSchema>;
export type PokemonRetrieveData = z.infer<typeof PokemonRetrieveDataSchema>;
export type PokemonRetrieveHookOverrides = OpenApiHookOverrides<PokemonRetrieveParams, PokemonRetrieveData>;
