/* Generated by react-networking-generate — do not edit. */
import { resolveOpenApiRequest, validateOpenApiParams, validateOpenApiResponse, resolveOpenApiSdkValidate, type OpenApiSdkCallOptions } from '@react33/react-networking';
import type { RequestReturn } from '@react33/react-networking';
import { pokemonRequest } from './apis.generated';
import { PokemonListDataSchema, PokemonRetrieveDataSchema, PokemonListParamsSchema, PokemonRetrieveParamsSchema } from './pokemon.openapi.zod';
import type { PokemonListParams, PokemonListData, PokemonRetrieveParams, PokemonRetrieveData } from './pokemon.openapi.types';

/**
 * @openapi-security cookieAuth, basicAuth
 * @openapi-security-schemes cookieAuth (apiKey cookie); basicAuth (http basic)
 * Wire auth via createApiRegistry loads for this scope (AuthProfile / LoadRequestProps).
 * @openapi-scope pokemon
 */
export const pokemon_listValidateDefaults = {"params":true,"response":true,"mode":"log"} as const;

export async function pokemon_list(
  params: PokemonListParams,
  options?: OpenApiSdkCallOptions,
): Promise<RequestReturn<PokemonListData>> {
  const validateOpts = resolveOpenApiSdkValidate(pokemon_listValidateDefaults, options?.validate);
  const verbose = options?.verbose ?? true;
  let requestParams = params;
  if (validateOpts.params) {
    requestParams = validateOpenApiParams(PokemonListParamsSchema, params, {
      operationId: "pokemon_list",
      schemaName: "PokemonListParamsSchema",
      direction: 'params',
      mode: validateOpts.mode,
      verbose,
      scope: "pokemon",
      method: "GET",
      url: "/pokemon/",
    });
  }
  const { url, body } = resolveOpenApiRequest("/pokemon/", "GET", requestParams);
  return pokemonRequest({
    url,
    method: "GET",
    body,
  }).then((res) => {
    if (validateOpts.response) {
      return validateOpenApiResponse(PokemonListDataSchema, res, {
        operationId: "pokemon_list",
        schemaName: "PokemonListDataSchema",
        direction: 'response',
        mode: validateOpts.mode,
        verbose,
        scope: "pokemon",
        method: "GET",
        url: "/pokemon/",
      });
    }
    return res;
  }) as Promise<RequestReturn<PokemonListData>>;
}

export const pokemon_listOpenApiMeta = {
  operationId: "pokemon_list",
  isPublic: false,
  securitySchemes: ["cookieAuth","basicAuth"],
} as const;

/**
 * @openapi-security cookieAuth, basicAuth
 * @openapi-security-schemes cookieAuth (apiKey cookie); basicAuth (http basic)
 * Wire auth via createApiRegistry loads for this scope (AuthProfile / LoadRequestProps).
 * @openapi-scope pokemon
 */
export const pokemon_retrieveValidateDefaults = {"params":true,"response":false,"mode":"log"} as const;

export async function pokemon_retrieve(
  params: PokemonRetrieveParams,
  options?: OpenApiSdkCallOptions,
): Promise<RequestReturn<PokemonRetrieveData>> {
  const validateOpts = resolveOpenApiSdkValidate(pokemon_retrieveValidateDefaults, options?.validate);
  const verbose = options?.verbose ?? true;
  let requestParams = params;
  if (validateOpts.params) {
    requestParams = validateOpenApiParams(PokemonRetrieveParamsSchema, params, {
      operationId: "pokemon_retrieve",
      schemaName: "PokemonRetrieveParamsSchema",
      direction: 'params',
      mode: validateOpts.mode,
      verbose,
      scope: "pokemon",
      method: "GET",
      url: "/pokemon/{id}/",
    });
  }
  const { url, body } = resolveOpenApiRequest("/pokemon/{id}/", "GET", requestParams);
  return pokemonRequest({
    url,
    method: "GET",
    body,
  }).then((res) => {
    if (validateOpts.response) {
      return validateOpenApiResponse(PokemonRetrieveDataSchema, res, {
        operationId: "pokemon_retrieve",
        schemaName: "PokemonRetrieveDataSchema",
        direction: 'response',
        mode: validateOpts.mode,
        verbose,
        scope: "pokemon",
        method: "GET",
        url: "/pokemon/{id}/",
      });
    }
    return res;
  }) as Promise<RequestReturn<PokemonRetrieveData>>;
}

export const pokemon_retrieveOpenApiMeta = {
  operationId: "pokemon_retrieve",
  isPublic: false,
  securitySchemes: ["cookieAuth","basicAuth"],
} as const;
