/* eslint-disable */
/* Generated by react-networking-generate — do not edit. */

import type { PokemonListData, PokemonRetrieveData } from './pokemon.openapi.types';

export const emptyPokemonListData = { count: 0, results: [] } satisfies PokemonListData;

export const emptyPokemonRetrieveData = { abilities: [], cries: { latest: '', legacy: '' }, forms: [], game_indices: [], held_items: [], id: 0, location_area_encounters: '', moves: [], name: '', past_abilities: [], past_stats: '', past_types: [], species: { name: '', url: '' }, sprites: { front_default: '' }, stats: [], types: [] } satisfies PokemonRetrieveData;
