'use client';
/* Generated by react-networking-generate — do not edit. */
import { usePokemonRequest } from './apis.client.generated';
import type { RequestReturn } from '@react33/react-networking';
import type { PokemonListHookOverrides, PokemonListParams, PokemonListData, PokemonRetrieveHookOverrides, PokemonRetrieveParams, PokemonRetrieveData } from './pokemon.openapi.types';
import { pokemon_list, pokemon_retrieve } from './pokemon.openapi';
import { emptyPokemonListData } from './pokemon.init-data';

/**
 * @openapi-security cookieAuth, basicAuth
 * @openapi-security-schemes cookieAuth (apiKey cookie); basicAuth (http basic)
 * Wire auth via createApiRegistry loads for this scope (AuthProfile / LoadRequestProps).
 * @openapi-scope pokemon
 */
export function usePokemonList(
  options?: PokemonListHookOverrides,
  watch: unknown[] = [],
) {
  return usePokemonRequest<PokemonListParams, PokemonListData>({
    name: "pokemon_list",
    url: "/pokemon/",
    method: "GET",
    fetchOnMount: true,
    verbose: true,
    initData: emptyPokemonListData,
    action: async (params) => pokemon_list(params as PokemonListParams, { verbose: options?.verbose ?? true }) as Promise<RequestReturn<PokemonListData>>,
    ...options,
  }, watch);
}

/**
 * @openapi-security cookieAuth, basicAuth
 * @openapi-security-schemes cookieAuth (apiKey cookie); basicAuth (http basic)
 * Wire auth via createApiRegistry loads for this scope (AuthProfile / LoadRequestProps).
 * @openapi-scope pokemon
 */
export function usePokemonRetrieve(
  options?: PokemonRetrieveHookOverrides,
  watch: unknown[] = [],
) {
  return usePokemonRequest<PokemonRetrieveParams, PokemonRetrieveData>({
    name: "pokemon_retrieve",
    url: "/pokemon/{id}/",
    method: "GET",
    fetchOnMount: false,
    verbose: true,
    
    action: async (params) => pokemon_retrieve(params as PokemonRetrieveParams, { verbose: options?.verbose ?? true }) as Promise<RequestReturn<PokemonRetrieveData>>,
    ...options,
  }, watch);
}
