/* Generated by react-networking-generate — do not edit. */
import { z } from 'zod';

export const PokemonListParamsSchema = z.object({
    query: z.object({ limit: z.number().int().optional(), offset: z.number().int().optional(), q: z.string().optional() }).optional(),
  });
export const PokemonListDataSchema = z.object({
    count: z.number().int(),
    next: z.string().url().nullable().optional(),
    previous: z.string().url().nullable().optional(),
    results: z.array(z.object({
    name: z.string().max(200),
    url: z.string().url(),
  })),
  });
export const PokemonRetrieveParamsSchema = z.object({
    path: z.object({ id: z.string() }),
  });
export const PokemonRetrieveDataSchema = z.object({
    id: z.number().int(),
    name: z.string().max(200),
    base_experience: z.number().int().min(-2147483648).max(2147483647).nullable().optional(),
    height: z.number().int().min(-2147483648).max(2147483647).nullable().optional(),
    is_default: z.boolean().optional(),
    order: z.number().int().min(-2147483648).max(2147483647).nullable().optional(),
    weight: z.number().int().min(-2147483648).max(2147483647).nullable().optional(),
    abilities: z.array(z.object({
    ability: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    is_hidden: z.boolean(),
    slot: z.number().int(),
  })),
    past_abilities: z.array(z.object({
    abilities: z.array(z.object({
    ability: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    is_hidden: z.boolean(),
    slot: z.number().int(),
  })),
    generation: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
  })),
    forms: z.array(z.object({
    name: z.string().max(200),
    url: z.string().url(),
  })),
    game_indices: z.array(z.object({
    game_index: z.number().int().min(-2147483648).max(2147483647),
    version: z.object({
    name: z.string().max(200),
    url: z.string().url(),
  }),
  })),
    held_items: z.array(z.object({
    item: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    version_details: z.array(z.object({
    rarity: z.number().int(),
    version: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
  })),
  })),
    location_area_encounters: z.string(),
    moves: z.array(z.object({
    move: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    version_group_details: z.array(z.object({
    level_learned_at: z.number().int(),
    move_learn_method: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    version_group: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
  })),
  })),
    species: z.object({
    name: z.string().max(200),
    url: z.string().url(),
  }),
    sprites: z.object({
    front_default: z.string().url().optional(),
  }),
    cries: z.object({
    latest: z.string().url(),
    legacy: z.string().url(),
  }),
    stats: z.array(z.object({
    base_stat: z.number().int().min(-2147483648).max(2147483647),
    effort: z.number().int().min(-2147483648).max(2147483647),
    stat: z.object({
    name: z.string().max(200),
    url: z.string().url(),
  }),
  })),
    past_stats: z.string(),
    types: z.array(z.object({
    slot: z.number().int(),
    type: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
  })),
    past_types: z.array(z.object({
    generation: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
    types: z.array(z.object({
    slot: z.number().int(),
    type: z.object({
    name: z.string(),
    url: z.string().url(),
  }),
  })),
  })),
  });