/* GENERATED by react-session-generate (@react33/react-session). Do not edit. */

import type { ApiRuntime } from '@react33/react-networking';
import { createBearerSessionManager, createBearerSessionLoad, createBearerSessionRetry, createBearerStaticSessionManager, createBearerStaticSessionLoad } from '@react33/react-session';
import * as mainSeam from "./main.session.runtime";
import * as partnerSeam from "./partner.session.runtime";
import * as kioskSeam from "./kiosk.session.runtime";

export const mainSession = createBearerSessionManager({
  storageKey: "demo.app.session",
  storage: "localStorage",
  accessTokenSkewSec: 30,
  selectors: mainSeam.selectors,
  refresh: mainSeam.refresh,
});
const mainLoad = createBearerSessionLoad(mainSession, { headers: {"Authorization":"Bearer {token}"}, proactiveRefresh: true });

// External session "partner" — the load is supplied by the seam (third-party SDK, token exchange, …).
const partnerLoad = partnerSeam.load;

export const kioskSession = createBearerStaticSessionManager({
  storage: "sessionStorage",
  storageKey: "demo.kiosk.token",
  selectors: kioskSeam.selectors,
});
const kioskLoad = createBearerStaticSessionLoad(kioskSession);

export const apiRuntime: ApiRuntime = {
  loads: {
    billing: mainLoad,
    reports: partnerLoad,
    catalog: kioskLoad,
  },
  defaultsByApi: {
    billing: createBearerSessionRetry(mainSession, { statuses: {"401":1}, tokenExpiredCode: "TOKEN_EXPIRED" }),
  },
};
