/* GENERATED by react-session-generate (@react33/react-session). Do not edit. */

'use client';

import { createSessionRuntime } from '@react33/react-session/runtime';
import { mainSession } from "./session.runtime.generated";

export const { SessionProvider, useSession, useSessionState } = createSessionRuntime({
  session: mainSession,
});
