import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { readReact33ThemeConfig, type React33ThemeConfig } from './read-react33-theme-config.js';

export const THEME_RUNTIME_BANNER =
  '/* GENERATED by react-theme-generate (@react33/react-theme). Do not edit. */';

/** Default env override when `persistenceEnvKey` is omitted in react33Theme. Set `""` in config to disable. */
export const DEFAULT_THEME_PERSISTENCE_ENV_KEY = 'REACT33_THEME_PERSISTENCE';

function quote(s: string): string {
  return JSON.stringify(s);
}

export function emitThemeRuntimeGeneratedSource(
  config: React33ThemeConfig,
  stylesImportPath: string,
): string {
  const persistenceMode = config.persistenceMode ?? 'localStorage';
  const cookieName = config.cookieName ?? config.localStorageKey ?? 'theme';
  const localStorageKey = config.localStorageKey ?? config.cookieName ?? 'theme';
  const cookiePath = config.cookiePath ?? '/';
  const cookieMaxAge = config.cookieMaxAgeSeconds ?? 60 * 60 * 24 * 365;
  const cookieSameSite = config.cookieSameSite ?? 'lax';
  const persistenceEnvKey =
    config.persistenceEnvKey === ''
      ? undefined
      : (config.persistenceEnvKey ?? DEFAULT_THEME_PERSISTENCE_ENV_KEY);
  const persistenceEnvKeyLine = persistenceEnvKey
    ? `  persistenceEnvKey: ${quote(persistenceEnvKey)},`
    : '';

  return [
    THEME_RUNTIME_BANNER,
    '',
    "'use client';",
    '',
    "import { createThemeRuntime } from '@react33/react-theme';",
    "import { createThemePersistence } from '@react33/react-theme/persistence';",
    `import { styles, type ThemeName } from ${quote(stylesImportPath)};`,
    '',
    '/** Env override: REACT33_* must reach the client — see docs/persistence-env-client.en.md */',
    'const themePersistence = createThemePersistence<ThemeName>({',
    `  defaultTheme: styles.meta.defaultTheme,`,
    `  persistenceMode: ${quote(persistenceMode)},`,
    `  cookieName: ${quote(cookieName)},`,
    `  localStorageKey: ${quote(localStorageKey)},`,
    persistenceEnvKeyLine,
    `  cookiePath: ${quote(cookiePath)},`,
    `  cookieMaxAgeSeconds: ${cookieMaxAge},`,
    `  cookieSameSite: ${quote(cookieSameSite)},`,
    '});',
    '',
    'export const THEME_PERSISTENCE_MODE = themePersistence.persistenceMode;',
    'export const THEME_STORAGE_KEY = themePersistence.storageKey;',
    'export const getInitialTheme = themePersistence.getInitialTheme;',
    'export const persistTheme = themePersistence.persistTheme;',
    '',
    'export const {',
    '  ThemeProvider,',
    '  ThemeBodySync,',
    '  useTheme,',
    '  useThemeState,',
    '  useThemeUpdater,',
    '} = createThemeRuntime<ThemeName>({',
    '  defaultTheme: styles.meta.defaultTheme,',
    '});',
    '',
    'export { styles, type ThemeName };',
    '',
  ].join('\n');
}

export type WriteThemeRuntimeFromConfigResult = {
  skipped: boolean;
  outputPath?: string;
};

export function writeThemeRuntimeFromConfig(options: {
  configPath: string;
  cwd?: string;
}): WriteThemeRuntimeFromConfigResult {
  const cwd = options.cwd ?? process.cwd();
  const configPath = resolve(cwd, options.configPath);
  const configDir = dirname(configPath);
  const raw = JSON.parse(readFileSync(configPath, 'utf8')) as unknown;
  const config = readReact33ThemeConfig(raw);
  if (!config) {
    return { skipped: true };
  }

  const outRel = config.runtimeOutput ?? './src/theme/theme.runtime.generated.ts';
  const outputPath = resolve(configDir, outRel);
  const stylesImportPath = config.stylesModule ?? './styles.generated';

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    emitThemeRuntimeGeneratedSource(config, stylesImportPath),
    'utf8',
  );
  return { skipped: false, outputPath };
}
