const NAME_RE = /^[a-zA-Z][a-zA-Z0-9_]*$/;

function assertValidApiName(name: string): void {
  if (!NAME_RE.test(name)) {
    throw new Error(
      `Invalid api name "${name}": use a letter-first identifier [a-zA-Z][a-zA-Z0-9_]*`,
    );
  }
}

/** `pokemon` → `Pokemon` for `usePokemonRequest`. */
function toPascalCase(apiName: string): string {
  return apiName.charAt(0).toUpperCase() + apiName.slice(1);
}

/**
 * `apis.generated.ts` → `apis.client.generated.tsx` (client hooks) in the same directory.
 * Other `*.ts` outputs → `*.client.generated.tsx` beside them.
 */
export function deriveHooksGeneratedPath(apisModulePath: string): string {
  if (apisModulePath.endsWith('apis.generated.ts')) {
    return apisModulePath.replace(/apis\.generated\.ts$/, 'apis.client.generated.tsx');
  }
  return apisModulePath.replace(/\.ts$/i, '.client.generated.tsx');
}

/** Optional `registryOutput` / `hooksOutput` under `react33Networking` in `react33.config.json` (write paths relative to the config file). */
export function readReact33NetworkingOutputPaths(configJson: unknown): {
  registryOutput?: string;
  hooksOutput?: string;
} {
  const root = configJson as Record<string, unknown> | null;
  const react33Networking = root?.react33Networking as Record<string, unknown> | undefined;
  if (!react33Networking || typeof react33Networking !== 'object') return {};
  return {
    registryOutput:
      typeof react33Networking.registryOutput === 'string'
        ? react33Networking.registryOutput
        : undefined,
    hooksOutput:
      typeof react33Networking.hooksOutput === 'string' ? react33Networking.hooksOutput : undefined,
  };
}

/** Subset of `RequestInit` allowed in `react33.config.json` for each API. */
export type ApiDefinitionJson = {
  url: string;
  headers?: Record<string, string>;
  cache?: 'default' | 'no-store' | 'reload' | 'no-cache' | 'force-cache' | 'only-if-cached';
  credentials?: 'omit' | 'same-origin' | 'include';
  /**
   * Name of the `react33Session.sessions` entry that authenticates this API (the api→session
   * foreign key). Consumed by the `@react33/react-session` codegen to build the per-API `loads`
   * map; the networking codegen itself ignores it. Omit for an unauthenticated API.
   */
  session?: string;
};

/** One property in `definitions` — key is the API name (see `createApiRegistry` map form). */
function formatMapProperty(name: string, m: ApiDefinitionJson): string {
  const headers = {
    Accept: 'application/json',
    ...(m.headers ?? {}),
  };
  const lines: string[] = [
    `  ${name}: {`,
    `    url: ${JSON.stringify(m.url)},`,
    `    headers: ${JSON.stringify(headers)},`,
  ];
  lines.push(`    cache: ${JSON.stringify(m.cache ?? 'no-store')},`);
  if (m.credentials !== undefined) {
    lines.push(`    credentials: ${JSON.stringify(m.credentials)},`);
  }
  lines.push('  },');
  return lines.join('\n');
}

function collectApiNames(configJson: unknown): string[] {
  const root = configJson as Record<string, unknown> | null;
  const react33Networking = root?.react33Networking as Record<string, unknown> | undefined;
  const apis = react33Networking?.apis;
  if (apis === undefined || apis === null) {
    return [];
  }
  if (typeof apis !== 'object' || Array.isArray(apis)) {
    throw new Error(
      'react33.config.json: react33Networking.apis must be an object (name -> config), not an array',
    );
  }
  const names: string[] = [];
  for (const name of Object.keys(apis)) {
    assertValidApiName(name);
    names.push(name);
  }
  return names;
}

/**
 * Client hooks: `usePokemonRequest` → `useAsyncFetch` + `apis.pokemon`.
 * Written next to `apis.generated.ts` (see `deriveHooksGeneratedPath`).
 */
export function generateApisHooksModuleSource(configJson: unknown): string {
  const names = collectApiNames(configJson);

  if (names.length === 0) {
    return `'use client';

/* Generated by react-networking-generate — do not edit */

import { apis } from './apis.generated';

void apis;

export {};
`;
  }

  const hooks = names
    .map((name) => {
      const pascal = toPascalCase(name);
      return `export function use${pascal}Request<Params, Data, Response = null>(
  settings: DynamicOptions<Params, Data, Response>,
  watch: unknown[] = [],
) {
  const { action: settingsAction, url = '/', method = 'GET', ...rest } = settings;
  const action =
    settingsAction ??
    (async (params?: Params) =>
      apis.${name}({ url, method, body: params }) as unknown as Promise<RequestReturn<Data>>);
  return useAsyncFetch<Params, Data, Response>(
    {
      ...rest,
      url,
      method,
      action,
    },
    watch,
  );
}`;
    })
    .join('\n\n');

  return `'use client';

/* Generated by react-networking-generate — do not edit */

import { useAsyncFetch, type DynamicOptions, type RequestReturn } from '@react33/react-networking';
import { apis } from './apis.generated';

${hooks}
`;
}

/**
 * Build the TypeScript source for `apis` + per-API `*Request` clients from parsed `react33.config.json` (or similar).
 * Expects `react33Networking.apis` to be an **object** keyed by API name (not an array).
 */
export function generateApisModuleSource(configJson: unknown): string {
  const root = configJson as Record<string, unknown> | null;
  const react33Networking = root?.react33Networking as Record<string, unknown> | undefined;
  const apis = react33Networking?.apis;
  const runtimeModule =
    typeof react33Networking?.runtimeModule === 'string' &&
    react33Networking.runtimeModule.length > 0
      ? react33Networking.runtimeModule
      : undefined;

  if (apis === undefined || apis === null) {
    return `/* Generated by react-networking-generate — do not edit */
import { createApiRegistry, type ApiClientConfigBody } from '@react33/react-networking';

export const definitions = {} satisfies Record<string, ApiClientConfigBody>;

export const apis = createApiRegistry(definitions, {
  load: async (shared) => shared,
});

export type ApiNames = keyof typeof apis;
`;
  }

  if (typeof apis !== 'object' || Array.isArray(apis)) {
    throw new Error(
      'react33.config.json: react33Networking.apis must be an object (name -> config), not an array',
    );
  }

  const props: string[] = [];
  const names: string[] = [];
  for (const [name, meta] of Object.entries(apis)) {
    assertValidApiName(name);
    if (!meta || typeof meta !== 'object' || !('url' in (meta as object))) {
      throw new Error(`react33Networking.apis.${name}: expected object with url`);
    }
    const m = meta as ApiDefinitionJson;
    if (typeof m.url !== 'string') {
      throw new Error(`react33Networking.apis.${name}.url must be a string`);
    }
    names.push(name);
    props.push(formatMapProperty(name, m));
  }

  const definitionsBlock = props.join('\n');

  const definitionsLiteral =
    props.length === 0
      ? '{}'
      : `{
${definitionsBlock}
}`;

  const requestExports =
    names.length > 0
      ? `\n${names.map((n) => `export const ${n}Request = apis.${n};`).join('\n')}\n`
      : '\n';

  if (runtimeModule !== undefined) {
    return `/* eslint-disable */
/* Generated by react-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@react33/react-networking';
import { apiRuntime } from ${JSON.stringify(runtimeModule)};

const baseDefinitions = ${definitionsLiteral} satisfies Record<string, ApiClientConfigBody>;

export const definitions = apiRuntime.defineDefinitions?.(baseDefinitions) ?? baseDefinitions;

export const apis = createApiRegistry(definitions, {
  load: apiRuntime.load,
  loads: apiRuntime.loads,
  defaults: apiRuntime.defaults,
  defaultsByApi: apiRuntime.defaultsByApi,
});

export type ApiNames = keyof typeof apis;${requestExports}`;
  }

  return `/* eslint-disable */
/* Generated by react-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@react33/react-networking';

export const definitions = ${definitionsLiteral} satisfies Record<string, ApiClientConfigBody>;

export const apis = createApiRegistry(definitions, {
  load: async (shared) => shared,
});

export type ApiNames = keyof typeof apis;${requestExports}`;
}
