const NAME_RE = /^[a-zA-Z][a-zA-Z0-9_]*$/;

function assertValidApiName(name: string): void {
  if (!NAME_RE.test(name)) {
    throw new Error(
      `Invalid api name "${name}": use a letter-first identifier [a-zA-Z][a-zA-Z0-9_]*`,
    );
  }
}

/** `pokemon` → `Pokemon` for `usePokemonRequest`. */
function toPascalCase(apiName: string): string {
  return apiName.charAt(0).toUpperCase() + apiName.slice(1);
}

/**
 * `apis.generated.ts` → `apis.client.generated.tsx` (client hooks) in the same directory.
 * Other `*.ts` outputs → `*.client.generated.tsx` beside them.
 */
export function deriveHooksGeneratedPath(apisModulePath: string): string {
  if (apisModulePath.endsWith('apis.generated.ts')) {
    return apisModulePath.replace(/apis\.generated\.ts$/, 'apis.client.generated.tsx');
  }
  return apisModulePath.replace(/\.ts$/i, '.client.generated.tsx');
}

/** Optional `output` / `hooksOutput` under `libNetworking` in `lib.config.json` (paths relative to the config file). */
export function readLibNetworkingOutputPaths(configJson: unknown): {
  output?: string;
  hooksOutput?: string;
} {
  const root = configJson as Record<string, unknown> | null;
  const libNetworking = root?.libNetworking as Record<string, unknown> | undefined;
  if (!libNetworking || typeof libNetworking !== 'object') return {};
  return {
    output: typeof libNetworking.output === 'string' ? libNetworking.output : undefined,
    hooksOutput: typeof libNetworking.hooksOutput === 'string' ? libNetworking.hooksOutput : undefined,
  };
}

/** Subset of `RequestInit` allowed in `lib.config.json` for each API. */
export type ApiDefinitionJson = {
  url: string;
  headers?: Record<string, string>;
  cache?: 'default' | 'no-store' | 'reload' | 'no-cache' | 'force-cache' | 'only-if-cached';
  credentials?: 'omit' | 'same-origin' | 'include';
};

/** One property in `definitions` — key is the API name (see `createApiRegistry` map form). */
function formatMapProperty(name: string, m: ApiDefinitionJson): string {
  const headers = {
    Accept: 'application/json',
    ...(m.headers ?? {}),
  };
  const lines: string[] = [
    `  ${name}: {`,
    `    url: ${JSON.stringify(m.url)},`,
    `    headers: ${JSON.stringify(headers)},`,
  ];
  lines.push(`    cache: ${JSON.stringify(m.cache ?? 'no-store')},`);
  if (m.credentials !== undefined) {
    lines.push(`    credentials: ${JSON.stringify(m.credentials)},`);
  }
  lines.push('  },');
  return lines.join('\n');
}

function collectApiNames(configJson: unknown): string[] {
  const root = configJson as Record<string, unknown> | null;
  const libNetworking = root?.libNetworking as Record<string, unknown> | undefined;
  const apis = libNetworking?.apis;
  if (apis === undefined || apis === null) {
    return [];
  }
  if (typeof apis !== 'object' || Array.isArray(apis)) {
    throw new Error(
      'lib.config.json: libNetworking.apis must be an object (name -> config), not an array',
    );
  }
  const names: string[] = [];
  for (const name of Object.keys(apis)) {
    assertValidApiName(name);
    names.push(name);
  }
  return names;
}

/**
 * Client hooks: `usePokemonRequest` → `useAsyncFetch` + `apis.pokemon`.
 * Written next to `apis.generated.ts` (see `deriveHooksGeneratedPath`).
 */
export function generateApisHooksModuleSource(configJson: unknown): string {
  const names = collectApiNames(configJson);

  if (names.length === 0) {
    return `'use client';

/* Generated by lib-networking-generate — do not edit */

import { apis } from './apis.generated';

void apis;

export {};
`;
  }

  const hooks = names
    .map((name) => {
      const pascal = toPascalCase(name);
      return `export function use${pascal}Request<Params, Data, Response = null>(
  settings: DynamicOptions<Params, Data, Response>,
  watch: any[],
) {
  const { url = '/', method = 'GET' } = settings;
  return useAsyncFetch<Params, Data, Response>(
    {
      ...settings,
      action: async (params?: Params) =>
        apis.${name}({ url, method, body: params }) as unknown as Promise<RequestReturn<Data>>,
    },
    watch,
  );
}`;
    })
    .join('\n\n');

  return `'use client';

/* Generated by lib-networking-generate — do not edit */

import { useAsyncFetch, type DynamicOptions, type RequestReturn } from '@lib/networking';
import { apis } from './apis.generated';

${hooks}
`;
}

/**
 * Build the TypeScript source for `apis` + per-API `*Request` clients from parsed `lib.config.json` (or similar).
 * Expects `libNetworking.apis` to be an **object** keyed by API name (not an array).
 */
export function generateApisModuleSource(configJson: unknown): string {
  const root = configJson as Record<string, unknown> | null;
  const libNetworking = root?.libNetworking as Record<string, unknown> | undefined;
  const apis = libNetworking?.apis;

  if (apis === undefined || apis === null) {
    return `/* Generated by lib-networking-generate — do not edit */
import { createApiRegistry, type ApiClientConfigBody } from '@lib/networking';

export const definitions = {} satisfies Record<string, ApiClientConfigBody>;

export const apis = createApiRegistry(definitions, {
  load: async (shared) => shared,
});

export type ApiNames = keyof typeof apis;
`;
  }

  if (typeof apis !== 'object' || Array.isArray(apis)) {
    throw new Error(
      'lib.config.json: libNetworking.apis must be an object (name -> config), not an array',
    );
  }

  const props: string[] = [];
  const names: string[] = [];
  for (const [name, meta] of Object.entries(apis)) {
    assertValidApiName(name);
    if (!meta || typeof meta !== 'object' || !('url' in (meta as object))) {
      throw new Error(`libNetworking.apis.${name}: expected object with url`);
    }
    const m = meta as ApiDefinitionJson;
    if (typeof m.url !== 'string') {
      throw new Error(`libNetworking.apis.${name}.url must be a string`);
    }
    names.push(name);
    props.push(formatMapProperty(name, m));
  }

  const definitionsBlock = props.join('\n');

  const definitionsLiteral =
    props.length === 0
      ? '{}'
      : `{
${definitionsBlock}
}`;

  const requestExports =
    names.length > 0
      ? `\n${names.map((n) => `export const ${n}Request = apis.${n};`).join('\n')}\n`
      : '\n';

  return `/* eslint-disable */
/* Generated by lib-networking-generate — do not edit */

import { createApiRegistry, type ApiClientConfigBody } from '@lib/networking';

export const definitions = ${definitionsLiteral} satisfies Record<string, ApiClientConfigBody>;

export const apis = createApiRegistry(definitions, {
  load: async (shared) => shared,
});

export type ApiNames = keyof typeof apis;${requestExports}`;
}
