/**
 * Code generator for `@react33/react-session`. Turns the `react33Session` collection in
 * `react33.config.json` into two modules:
 *
 *   - `session.runtime.generated.ts`        — framework-agnostic, server-safe: the session
 *     managers + `apiRuntime` (`loads` / `defaultsByApi`). `react33Networking.runtimeModule`
 *     points here.
 *   - `session.runtime.client.generated.ts` — `'use client'`: `SessionProvider` +
 *     `useSession` / `useSessionState` for the `primarySession`. Emitted only when a
 *     `primarySession` is declared.
 *
 * The split keeps the React boundary out of the server-safe seam — see the package README.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import {
  readReact33SessionConfig,
  type React33SessionConfig,
  type SessionDef,
  type SessionRetryConfig,
} from './read-react33-session-config.js';

export const SESSION_RUNTIME_BANNER =
  '/* GENERATED by react-session-generate (@react33/react-session). Do not edit. */';

function quote(s: string): string {
  return JSON.stringify(s);
}

const seamAlias = (name: string): string => `${name}Seam`;
const managerName = (name: string): string => `${name}Session`;
const loadName = (name: string): string => `${name}Load`;

function retryOptionsArg(retry: SessionRetryConfig): string {
  const parts: string[] = [];
  if (retry.statuses !== undefined) parts.push(`statuses: ${JSON.stringify(retry.statuses)}`);
  if (retry.tokenExpiredCode !== undefined) {
    parts.push(`tokenExpiredCode: ${quote(retry.tokenExpiredCode)}`);
  }
  return parts.length > 0 ? `, { ${parts.join(', ')} }` : '';
}

function emitBearerSession(s: SessionDef): string[] {
  const b = s.bearer ?? {};
  const managerOpts: string[] = [];
  if (b.storageKey !== undefined) managerOpts.push(`  storageKey: ${quote(b.storageKey)},`);
  if (b.storage !== undefined) managerOpts.push(`  storage: ${quote(b.storage)},`);
  if (b.accessTokenSkewSec !== undefined) {
    managerOpts.push(`  accessTokenSkewSec: ${b.accessTokenSkewSec},`);
  }
  managerOpts.push(`  selectors: ${seamAlias(s.name)}.selectors,`);
  managerOpts.push(`  refresh: ${seamAlias(s.name)}.refresh,`);

  const loadOpts: string[] = [];
  if (b.headers !== undefined) loadOpts.push(`headers: ${JSON.stringify(b.headers)}`);
  if (b.proactiveRefresh !== undefined) loadOpts.push(`proactiveRefresh: ${b.proactiveRefresh}`);
  const loadArg = loadOpts.length > 0 ? `, { ${loadOpts.join(', ')} }` : '';

  return [
    `export const ${managerName(s.name)} = createBearerSessionManager({`,
    ...managerOpts,
    '});',
    `const ${loadName(s.name)} = createBearerSessionLoad(${managerName(s.name)}${loadArg});`,
  ];
}

function emitBearerStaticSession(s: SessionDef): string[] {
  const b = s.bearerStatic ?? {};
  const managerOpts: string[] = [];
  if (b.storage !== undefined) managerOpts.push(`  storage: ${quote(b.storage)},`);
  if (b.storageKey !== undefined) managerOpts.push(`  storageKey: ${quote(b.storageKey)},`);
  if (b.accessTokenSkewSec !== undefined) {
    managerOpts.push(`  accessTokenSkewSec: ${b.accessTokenSkewSec},`);
  }
  managerOpts.push(`  selectors: ${seamAlias(s.name)}.selectors,`);

  const loadArg = b.headers !== undefined ? `, { headers: ${JSON.stringify(b.headers)} }` : '';

  return [
    `export const ${managerName(s.name)} = createBearerStaticSessionManager({`,
    ...managerOpts,
    '});',
    `const ${loadName(s.name)} = createBearerStaticSessionLoad(${managerName(s.name)}${loadArg});`,
  ];
}

function emitApiRuntime(config: React33SessionConfig): string[] {
  const sessionByName = new Map(config.sessions.map((s) => [s.name, s]));
  const apiNames = Object.keys(config.bindings);

  const loadEntries = apiNames.map(
    (api) => `    ${api}: ${loadName(config.bindings[api]!)},`,
  );

  const retryEntries: string[] = [];
  for (const api of apiNames) {
    const s = sessionByName.get(config.bindings[api]!);
    if (s && s.strategy === 'bearer' && s.retry) {
      retryEntries.push(
        `    ${api}: createBearerSessionRetry(${managerName(s.name)}${retryOptionsArg(s.retry)}),`,
      );
    }
  }

  const lines = ['export const apiRuntime: ApiRuntime = {'];
  if (loadEntries.length > 0) lines.push('  loads: {', ...loadEntries, '  },');
  if (retryEntries.length > 0) lines.push('  defaultsByApi: {', ...retryEntries, '  },');
  lines.push('};');
  return lines;
}

/** Emit the framework-agnostic generated module (managers + `apiRuntime`). */
export function emitSessionRuntimeAgnosticSource(config: React33SessionConfig): string {
  const bearerSessions = config.sessions.filter((s) => s.strategy === 'bearer');
  const anyBearer = bearerSessions.length > 0;
  const anyRetry = bearerSessions.some((s) => Boolean(s.retry));
  const anyBearerStatic = config.sessions.some((s) => s.strategy === 'bearer-static');

  const lines: string[] = [SESSION_RUNTIME_BANNER, '', "import type { ApiRuntime } from '@react33/react-networking';"];
  const named: string[] = [];
  if (anyBearer) {
    named.push('createBearerSessionManager', 'createBearerSessionLoad');
    if (anyRetry) named.push('createBearerSessionRetry');
  }
  if (anyBearerStatic) {
    named.push('createBearerStaticSessionManager', 'createBearerStaticSessionLoad');
  }
  if (named.length > 0) {
    lines.push(`import { ${named.join(', ')} } from '@react33/react-session';`);
  }
  for (const s of config.sessions) {
    lines.push(`import * as ${seamAlias(s.name)} from ${quote(s.runtimeModule)};`);
  }
  lines.push('');

  for (const s of config.sessions) {
    if (s.strategy === 'bearer') {
      lines.push(...emitBearerSession(s));
    } else if (s.strategy === 'bearer-static') {
      lines.push(...emitBearerStaticSession(s));
    } else {
      lines.push(
        `// External session "${s.name}" — the load is supplied by the seam (third-party SDK, token exchange, …).`,
        `const ${loadName(s.name)} = ${seamAlias(s.name)}.load;`,
      );
    }
    lines.push('');
  }

  lines.push(...emitApiRuntime(config), '');
  return lines.join('\n');
}

/** Module specifier the client file uses to import from the agnostic file (same directory). */
function agnosticModuleSpecifier(runtimeOutput: string): string {
  return `./${basename(runtimeOutput).replace(/\.tsx?$/i, '')}`;
}

/** Derive the `.client.generated` path from the agnostic `runtimeOutput` path. */
export function deriveSessionClientOutputPath(runtimeOutput: string): string {
  if (/\.generated\.tsx?$/i.test(runtimeOutput)) {
    return runtimeOutput.replace(/\.generated(\.tsx?)$/i, '.client.generated$1');
  }
  return runtimeOutput.replace(/(\.tsx?)$/i, '.client$1');
}

/**
 * Emit the `'use client'` React module for the `primarySession`. Returns `null` when no
 * `primarySession` is declared (the app has no react33 React session surface).
 */
export function emitSessionRuntimeClientSource(config: React33SessionConfig): string | null {
  if (!config.primarySession) return null;
  const primary = config.sessions.find((s) => s.name === config.primarySession);
  if (!primary) return null;

  const lines: string[] = [
    SESSION_RUNTIME_BANNER,
    '',
    "'use client';",
    '',
    "import { createSessionRuntime } from '@react33/react-session/runtime';",
  ];

  let sessionExpr: string;
  if (primary.strategy === 'bearer' || primary.strategy === 'bearer-static') {
    // Managed strategies export their manager from the agnostic file; it satisfies SessionStore.
    lines.push(
      `import { ${managerName(primary.name)} } from ${quote(agnosticModuleSpecifier(config.runtimeOutput))};`,
    );
    sessionExpr = managerName(primary.name);
  } else {
    // External primary: the React store comes straight from the seam (e.g. a Firebase adapter).
    lines.push(`import * as ${seamAlias(primary.name)} from ${quote(primary.runtimeModule)};`);
    sessionExpr = `${seamAlias(primary.name)}.sessionStore`;
  }

  lines.push(
    '',
    'export const { SessionProvider, useSession, useSessionState } = createSessionRuntime({',
    `  session: ${sessionExpr},`,
    '});',
    '',
  );
  return lines.join('\n');
}

export type WriteSessionRuntimeResult = {
  skipped: boolean;
  agnosticPath?: string;
  clientPath?: string;
};

/** Read `react33.config.json`, emit the agnostic module and (when primary) the client module. */
export function writeSessionRuntimeFromConfig(options: {
  configPath: string;
  cwd?: string;
}): WriteSessionRuntimeResult {
  const cwd = options.cwd ?? process.cwd();
  const configPath = resolve(cwd, options.configPath);
  const configDir = dirname(configPath);
  const raw = JSON.parse(readFileSync(configPath, 'utf8')) as unknown;
  const config = readReact33SessionConfig(raw);
  if (!config) return { skipped: true };

  const agnosticPath = resolve(configDir, config.runtimeOutput);
  mkdirSync(dirname(agnosticPath), { recursive: true });
  writeFileSync(agnosticPath, emitSessionRuntimeAgnosticSource(config), 'utf8');

  let clientPath: string | undefined;
  const clientSource = emitSessionRuntimeClientSource(config);
  if (clientSource) {
    clientPath = resolve(configDir, deriveSessionClientOutputPath(config.runtimeOutput));
    mkdirSync(dirname(clientPath), { recursive: true });
    writeFileSync(clientPath, clientSource, 'utf8');
  }
  return { skipped: false, agnosticPath, clientPath };
}
