import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, posix, resolve } from 'node:path';
import { loadLocaleModule } from './load-locale-module.js';

export { loadLocaleModule } from './load-locale-module.js';
export {
  readReact33I18nConfig,
  readReact33I18nConfigs,
  type React33I18nConfig,
} from './read-react33-i18n-config.js';
import {
  readReact33I18nConfigs,
  type React33I18nConfig,
} from './read-react33-i18n-config.js';

export const I18N_GENERATE_BANNER =
  '/* GENERATED by react-i18n-generate (@react33/react-i18n). Do not edit. */';

/** Default env override when `persistenceEnvKey` is omitted in react33I18n. Set `""` in config to disable. */
export const DEFAULT_I18N_PERSISTENCE_ENV_KEY = 'REACT33_I18N_PERSISTENCE';

export type LocaleStructure = Record<string, Record<string, string>>;

function quote(s: string): string {
  return JSON.stringify(s);
}

function toPascal(scope: string): string {
  return scope.charAt(0).toUpperCase() + scope.slice(1);
}

/** Top-level keys whose values are flat string maps (scopes). */
export function collectScopes(structure: Record<string, unknown>): string[] {
  const scopes: string[] = [];
  for (const [key, value] of Object.entries(structure)) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      const flat = Object.values(value as Record<string, unknown>).every(
        (x) => typeof x === 'string',
      );
      if (flat) scopes.push(key);
    }
  }
  return scopes;
}

export function flattenLocaleStructure(
  structure: Record<string, unknown>,
): LocaleStructure {
  const out: LocaleStructure = {};
  for (const scope of collectScopes(structure)) {
    const block = structure[scope];
    if (block && typeof block === 'object' && !Array.isArray(block)) {
      out[scope] = Object.fromEntries(
        Object.entries(block as Record<string, unknown>).filter(
          (entry): entry is [string, string] => typeof entry[1] === 'string',
        ),
      );
    }
  }
  return out;
}

export function emitI18nGeneratedSource(
  config: React33I18nConfig,
  localeStructure: LocaleStructure,
): string {
  const {
    defaultLocale,
    locales,
    cookieName,
    localStorageKey,
    persistenceMode,
    urlLocalePattern,
  } = config;

  const resolveOpts: Record<string, string | string[]> = {
    defaultLocale,
    allowedLocales: locales,
  };
  if (cookieName) resolveOpts.cookieName = cookieName;
  if (localStorageKey) resolveOpts.localStorageKey = localStorageKey;
  if (urlLocalePattern) resolveOpts.urlLocalePattern = urlLocalePattern;

  const scopes = Object.keys(localeStructure);
  const scopeList = scopes.length > 0 ? scopes : ['login'];

  const typeLines: string[] = [
    '',
    '/** Scopes present in the source locale module. */',
    `export type I18nScope = ${scopeList.map(quote).join(' | ')}`,
  ];

  const structureFields: string[] = [];
  for (const scope of scopeList) {
    const keys = Object.keys(localeStructure[scope] ?? {});
    const pascal = toPascal(scope);
    const messageKeyType = `${pascal}MessageKey`;
    const copyType = `${pascal}Copy`;
    if (keys.length > 0) {
      typeLines.push(
        '',
        `/** Message keys for scope \`${scope}\` (from source locale). */`,
        `export type ${messageKeyType} = ${keys.map(quote).join(' | ')}`,
        '',
        `export type ${copyType} = Record<${messageKeyType}, string>`,
      );
      structureFields.push(`${scope}: ${copyType}`);
    } else {
      structureFields.push(`${scope}: Record<string, string>`);
    }
  }

  typeLines.push('', `export type Structure = { ${structureFields.join('; ')} }`);

  return [
    I18N_GENERATE_BANNER,
    '',
    `export const ALLOWED_LOCALES = ${JSON.stringify(locales)} as const`,
    'export type Locale = (typeof ALLOWED_LOCALES)[number]',
    `export const DEFAULT_LOCALE = ${quote(defaultLocale)} as const satisfies Locale`,
    '',
    ...(cookieName ? [`export const I18N_COOKIE_NAME = ${quote(cookieName)} as const`] : []),
    ...(localStorageKey
      ? [`export const I18N_LOCAL_STORAGE_KEY = ${quote(localStorageKey)} as const`]
      : []),
    '',
    '/** Options for resolveInitialLocale (@react33/react-i18n). */',
    `export const resolveLocaleOptions = ${JSON.stringify(resolveOpts, null, 2)} as const`,
    typeLines.join('\n'),
    '',
  ].join('\n');
}

function relativeImport(fromDir: string, toAbs: string): string {
  const rel = posix.relative(fromDir, toAbs).replace(/\\/g, '/');
  const withoutExt = rel.replace(/\.(tsx?|jsx?)$/, '');
  if (withoutExt.startsWith('.')) return withoutExt;
  return `./${withoutExt}`;
}

export function emitI18nRuntimeGeneratedSource(
  config: React33I18nConfig,
  options: {
    typesImportPath: string;
    localeImports: { code: string; importPath: string }[];
  },
): string {
  if (config.runtimeMode === 'next') {
    throw new Error(
      'react-i18n-generate: runtimeMode "next" is not implemented yet; use "spa" or omit runtimeMode.',
    );
  }

  const {
    defaultLocale,
    locales,
    cookieName,
    localStorageKey,
    persistenceMode,
    urlLocalePattern,
  } = config;

  const cookie = cookieName ?? localStorageKey ?? 'locale';
  const storage = localStorageKey ?? cookieName ?? 'locale';
  const mode = persistenceMode ?? 'localStorage';

  const dictEntries = options.localeImports
    .map(({ code, importPath }) => `  ${code}: ${code}Messages,`)
    .join('\n');

  const localeImportLines = options.localeImports
    .map(
      ({ code, importPath }) =>
        `import ${code}Messages from ${quote(importPath)};`,
    )
    .join('\n');

  const urlPatternLine = urlLocalePattern
    ? `  urlLocalePattern: ${quote(urlLocalePattern)},`
    : '';
  const persistenceEnvKey =
    config.persistenceEnvKey === ''
      ? undefined
      : (config.persistenceEnvKey ?? DEFAULT_I18N_PERSISTENCE_ENV_KEY);
  const persistenceEnvKeyLine = persistenceEnvKey
    ? `  persistenceEnvKey: ${quote(persistenceEnvKey)},`
    : '';

  return [
    I18N_GENERATE_BANNER,
    '',
    "'use client';",
    '',
    "import { createLocaleRuntime, createLocalePersistence } from '@react33/react-i18n/client';",
    "import type { LocaleRuntime } from '@react33/react-i18n/client';",
    `import type { Locale, Structure } from ${quote(options.typesImportPath)};`,
    `import { DEFAULT_LOCALE } from ${quote(options.typesImportPath)};`,
    localeImportLines,
    '',
    'export const dictionaries = {',
    dictEntries,
    '} as const satisfies Record<Locale, Structure>;',
    '',
    '/** Env override: REACT33_* must reach the client — see docs/persistence-env-client.en.md */',
    'const localePersistence = createLocalePersistence({',
    `  defaultLocale: DEFAULT_LOCALE,`,
    `  allowedLocales: ${JSON.stringify(locales)},`,
    `  persistenceMode: ${quote(mode)},`,
    `  cookieName: ${quote(cookie)},`,
    `  localStorageKey: ${quote(storage)},`,
    persistenceEnvKeyLine,
    urlPatternLine,
    '});',
    '',
    'export const I18N_PERSISTENCE_MODE = localePersistence.persistenceMode;',
    'export const I18N_STORAGE_KEY = localePersistence.storageKey;',
    '',
    '/** Initial locale on first paint (URL → persistence → navigator → default). */',
    'export function getInitialLocale(): Locale {',
    '  return localePersistence.getInitialLocale() as Locale;',
    '}',
    '',
    'export function persistLocale(locale: Locale): void {',
    '  localePersistence.persistLocale(locale);',
    '}',
    '',
    'const localeRuntime: LocaleRuntime<Locale, Structure> = createLocaleRuntime<Locale, Structure>({',
    '  defaultLocale: DEFAULT_LOCALE,',
    '  dictionaries,',
    '});',
    '',
    'export const LocaleProvider = localeRuntime.LocaleProvider;',
    'export const useLocale = localeRuntime.useLocale;',
    'export const useDict: LocaleRuntime<Locale, Structure>["useDict"] = localeRuntime.useDict;',
    'export const useTf: LocaleRuntime<Locale, Structure>["useTf"] = localeRuntime.useTf;',
    'export const useAllLocale = localeRuntime.useAllLocale;',
    '',
  ].join('\n');
}

/** One emitted bundle's write paths (the map `name` when from a collection). */
export type WriteI18nBundleResult = {
  name?: string;
  outputPath: string;
  runtimeOutputPath: string;
};

export type WriteI18nFromConfigResult = {
  skipped: boolean;
  /** One entry per bundle (one for the flat form, N for a `bundles` map). */
  bundles: WriteI18nBundleResult[];
  /** First bundle's paths — back-compat for single-bundle callers. */
  outputPath?: string;
  runtimeOutputPath?: string;
};

/** Emit the types + runtime for a single bundle. */
async function writeI18nBundle(
  config: React33I18nConfig,
  configDir: string,
  loadLocale: typeof loadLocaleModule,
): Promise<WriteI18nBundleResult> {
  const localesDir = resolve(configDir, config.localesDir);
  const sourcePath = resolve(localesDir, `${config.defaultLocale}.ts`);
  let localeStructure: LocaleStructure = {};
  try {
    const structure = await loadLocale(sourcePath, config.defaultLocale);
    localeStructure = flattenLocaleStructure(structure);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(
      `react-i18n-generate: could not load ${sourcePath} for types (${message})`,
    );
  }

  const outRel = config.typesOutput ?? './src/lib/i18n/i18n.generated.ts';
  const outputPath = resolve(configDir, outRel);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    emitI18nGeneratedSource(config, localeStructure),
    'utf8',
  );

  const runtimeRel =
    config.runtimeOutput ?? './src/lib/i18n/i18n.runtime.generated.tsx';
  const runtimeOutputPath = resolve(configDir, runtimeRel);
  const runtimeDir = dirname(runtimeOutputPath);
  const typesImportPath = relativeImport(runtimeDir, outputPath);
  const localeImports = config.locales.map((code) => ({
    code,
    importPath: relativeImport(runtimeDir, resolve(localesDir, `${code}.ts`)),
  }));

  mkdirSync(runtimeDir, { recursive: true });
  writeFileSync(
    runtimeOutputPath,
    emitI18nRuntimeGeneratedSource(config, { typesImportPath, localeImports }),
    'utf8',
  );

  return {
    ...(config.name ? { name: config.name } : {}),
    outputPath,
    runtimeOutputPath,
  };
}

export async function writeI18nFromConfig(options: {
  configPath: string;
  cwd?: string;
  loadLocale?: typeof loadLocaleModule;
}): Promise<WriteI18nFromConfigResult> {
  const cwd = options.cwd ?? process.cwd();
  const configPath = resolve(cwd, options.configPath);
  const configDir = dirname(configPath);
  const raw = JSON.parse(readFileSync(configPath, 'utf8')) as unknown;
  const configs = readReact33I18nConfigs(raw);
  if (!configs) {
    return { skipped: true, bundles: [] };
  }

  const loadLocale = options.loadLocale ?? loadLocaleModule;
  const bundles: WriteI18nBundleResult[] = [];
  for (const config of configs) {
    bundles.push(await writeI18nBundle(config, configDir, loadLocale));
  }

  return {
    skipped: false,
    bundles,
    outputPath: bundles[0]?.outputPath,
    runtimeOutputPath: bundles[0]?.runtimeOutputPath,
  };
}
